version: '3.4'

services:
  frontend:
    container_name: rpgm-frontend
    build:
      context: ../services/frontend
      args:
        - REACT_APP_BACKEND_URL=http://backend.localtest.me:8080
    image: alef83/rpgm-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
  
  backend:
    container_name: rpgm-backend
    build: ../services/backend
    image: alef83/rpgm-backend
    depends_on:
      - core
    ports:
      - "8080:80"
    environment:
      - RPGM_COREAPIURL=http://core
      - RPGM_PORT=80
  
  core:
    container_name: rpgm-core
    build: ../services/core
    image: alef83/rpgm-core
    depends_on:
      - mongodb
    ports:
      - "8081:80"
    environment:
      - PORT=80

  mongodb:
    container_name: mongodb
    image: mongo:3.6.2-jessie
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USERNAME=game_master
      - MONGODB_PASSWORD=natural20
      - MONGODB_DATABASE=rpgm