version: '3.4'

services:
  frontend:
    container_name: rpgm-frontend
    build:
      context: ../services/frontend
      args:
        - REACT_APP_BACKEND_URL=http://backend.localtest.me:8080 
    image: alef83/rpgm-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
  
  backend:
    container_name: rpgm-backend
    build: ../services/backend
    image: alef83/rpgm-backend
    depends_on:
      - minio
      - solr
      - redis
    ports:
      - "8080:80"
    environment:
      - RPGM_CONNECTIONS_REDIS_ENDPOINT=redis:6379
      - RPGM_CONNECTIONS_MINIO_ENDPOINT=minio:9000
      - RPGM_CONNECTIONS_MINIO_BUCKETNAME=rpgm-bucket
      - RPGM_CONNECTIONS_MINIO_ACCESSKEYPATH=/run/secrets/minio_access_key
      - RPGM_CONNECTIONS_MINIO_SECRETKEYPATH=/run/secrets/minio_secret_key
      - RPGM_CONNECTIONS_SOLR_HOST=solr
      - RPGM_CONNECTIONS_SOLR_PORT=8983
      - PRMG_CONNECTIONS_SOLR_COLLECTIONAME=rpgm-collection
    secrets:
      - minio_access_key
      - minio_secret_key
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  minio:
    container_name:  minio
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data
    secrets:
      - source: minio_access_key
        target: access_key
      - source: minio_secret_key
        target: secret_key
  
  solr:
    container_name: solr
    image: solr
    ports:
      - "8983:8983"

secrets:
  minio_access_key:
    file: ./secrets/minio/access_key.txt
  minio_secret_key:
    file: ./secrets/minio/secret_key.txt