version: '3.4'

services:
  frontend:
    container_name: rpgm-frontend
    build: ../services/frontend
    image: alef83/rpgm-frontend
    depends_on:
      - backend
    ports:
      - "80:3000"
  
  backend:
    container_name: rpgm-backend
    build: ../services/backend
    image: alef83/rpgm-backend
    ports:
      - "8080:80"
  
  minio:
    container_name:  minio
    image: minio/minio
    ports:
      - "9000:9000"
  
  solr:
    container_name: solr
    image: solr
    ports:
      - "8983:8983"
