version: '3.4'

services:
  mongodb:
    volumes:
      - ../db/mongodb:/data/db
  
  redis:
    volumes:
      - ../db/redis:/data
  
  minio:
    volumes:
      - ../db/minio:/export

  backoffice:
    container_name: rpgm-backoffice
    build:
      context: ../utils/backoffice
      args:
        - REACT_APP_REDIS_URL=http://localhost:8101
        - REACT_APP_MINIO_URL=http://localhost:9000
        - REACT_APP_MONGODB_URL=http://localhost:8102
    depends_on:
      - minio
      - mongoExpress
      - redisCommander
    ports:
      - "8099:80"

  mongoExpress:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    links:
      - mongodb:mongo
    ports:
      - "8102:8081"

  redisCommander:
    container_name: redis-commander
    image: tenstartups/redis-commander
    depends_on:
      - redis
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8101:8081"