version: '3.5'

services:
  frontend:
    container_name: rpgm-frontend
    build:
      context: ../services/frontend
      args:
        - REACT_APP_BACKEND_URL=http://backend.localtest.me:8080
    image: alef83/rpgm-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
  
  backend:
    container_name: rpgm-backend
    build: ../services/backend
    image: alef83/rpgm-backend
    depends_on:
      - core
    ports:
      - "8080:80"
    environment:
      - RPGM_COREAPIURL=http://core
      - RPGM_PORT=80
  
  core:
    container_name: rpgm-core
    build: ../services/core
    image: alef83/rpgm-core
    ports:
      - "8081:80"
    environment:
      - PORT=80