version: '3.4'

services:
  frontend:
    container_name: rpgm-frontend
    build:
      context: ../services/frontend
      args:
        - REACT_APP_BACKEND_URL=http://backend.localtest.me:8080
    image: alef83/rpgm-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
  
  backend:
    container_name: rpgm-backend
    build: ../services/backend
    image: alef83/rpgm-backend
    depends_on:
      - core
      - minioInit
    ports:
      - "8080:80"
    environment:
      - RPGM_COREAPIURL=http://core
      - RPGM_PORT=80
  
  core:
    container_name: rpgm-core
    build: ../services/core
    image: alef83/rpgm-core
    depends_on:
      - mongodb
      - redis
      - minio
    ports:
      - "8081:80"
    environment:
      - PORT=80

  mongodb:
    container_name: mongodb
    image: mongo:3.6.2-jessie
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
  
  redis:
    container_name: redis
    image: redis:4.0.8-alpine
    ports:
      - "6379:6379"

  minio:
    container_name: minio
    image: minio/minio
    command: server /export
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  minioInit:
    container_name: minio-init
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add rpgm-minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc rm -r --force rpgm-minio/rpgm;
      /usr/bin/mc mb rpgm-minio/rpgm;
      /usr/bin/mc policy download rpgm-minio/rpgm;
      exit 0;
      "
    