export const AUTH_PROVIDERS_REQUEST = 'AUTH_PROVIDERS_REQUEST';
export const AUTH_PROVIDERS_SUCCESS = 'AUTH_PROVIDERS_SUCCESS';
export const AUTH_PROVIDERS_FAILURE = 'AUTH_PROVIDERS_FAILURE';

export const AUTH_TOKEN_RECEIVED = 'AUTH_TOKEN_RECEIVED';
