export const ENTITY_LIST_REQUEST = 'ENTITY_LIST_REQUEST';
export const ENTITY_LIST_SUCCESS = 'ENTITY_LIST_SUCCESS';
export const ENTITY_LIST_FAILURE = 'ENTITY_LIST_FAILURE';

export const ENTITY_LOAD_REQUEST = 'ENTITY_LOAD_REQUEST';
export const ENTITY_LOAD_SUCCESS = 'ENTITY_LOAD_SUCCESS';
export const ENTITY_LOAD_FAILURE = 'ENTITY_LOAD_FAILURE';

export const ENTITY_CREATE_REQUEST = 'ENTITY_CREATE_REQUEST';
export const ENTITY_CREATE_SUCCESS = 'ENTITY_CREATE_SUCCESS';
export const ENTITY_CREATE_FAILURE = 'ENTITY_CREATE_FAILURE';

export const ENTITY_UPDATE_REQUEST = 'ENTITY_UPDATE_REQUEST';
export const ENTITY_UPDATE_SUCCESS = 'ENTITY_UPDATE_SUCCESS';
export const ENTITY_UPDATE_FAILURE = 'ENTITY_UPDATE_FAILURE';

export const ENTITY_DELETE_REQUEST = 'ENTITY_DELETE_REQUEST';
export const ENTITY_DELETE_SUCCESS = 'ENTITY_DELETE_SUCCESS';
export const ENTITY_DELETE_FAILURE = 'ENTITY_DELETE_FAILURE';

export const ENTITY_MODE_CHANGE = 'ENTITY_MODE_CHANGE';
export const ENTITY_PROPERTY_CHANGE = 'ENTITY_PROPERTY_CHANGE';
