export const ENTITY_PROPERTY_ADDED = 'ENTITY_PROPERTY_ADDED';
export const ENTITY_PROPERTY_REMOVED = 'ENTITY_PROPERTY_REMOVED';
export const ENTITY_PROPERTY_CHANGED = 'ENTITY_PROPERTY_CHANGED';

export const ENTITY_SAVE_REQUEST = 'ENTITY_SAVE_REQUEST';
export const ENTITY_SAVE_SUCCESS = 'ENTITY_SAVE_SUCCESS';
export const ENTITY_SAVE_FAILURE = 'ENTITY_SAVE_FAILURE';
